In [5]:
import pandas as pd
import numpy as np
migration = pd.read_csv('./data/Wave 3 Server List.csv')
migration = migration.sort_values(by = ['App Name'])
snow = pd.read_csv('./data/ServiceNow.csv')
snow = snow.sort_values(by = ['name'])

In [8]:
migration.head(5)

,Server ID,App ID,App Name,Business Criticality,PLA Owner,L1 Capability,Environment,Normalized Env,Final Disposition
30,ghsacldb1w16v,APM0001678,ACL Suites,NaN,"Jones, Melissa M",Clinical,Production,Production,Rehost
29,ghsaclrbt1w19v,APM0001678,ACL Suites,NaN,"Jones, Melissa M",Clinical,Production,Production,Rehost
28,ghsaclapp1w16v,APM0001678,ACL Suites,NaN,"Jones, Melissa M",Clinical,Production,Production,Rehost
94,ghssdmongo1w16v,APM0002399,ADMI,NaN,"Temmel, Darryl J",Clinical,Production,Production,Net New
98,ghssdstg1w16v,APM0002399,ADMI,NaN,"Temmel, Darryl J",Clinical,Production,Production,Net New

In [42]:
snow['App Name'] = snow['name'] 
snow.head(5)

,name,u_data_manager,u_data_manager_designee,u_data_custodian,it_application_owner,business_criticality,App Name
0,ACL Suites,"Kerestus, Kevin J","Nevius, Aaron H","Cameron, Crystal L","Fisne, Joseph",High,ACL Suites
1,ADMI,"Martin, Christa Lese",NaN,"Trelease, Michael R","Fisne, Joseph",Low,ADMI
2,ADMI Screener,"Martin, Christa Lese",NaN,"Ditchey, Robert M","Fisne, Joseph",Low,ADMI Screener
3,Altimeter,"Yancoskie, Matthew M","Seibert, Michael J","Seibert, Michael J","Bennett, Daniel R",Low,Altimeter
4,Audiology Database,"Frymoyer, Timothy A",NaN,"Trelease, Michael R","Fisne, Joseph",Medium,Audiology Database

In [41]:
output = migration.copy(deep='True')

for index, row in snow.iterrows():
    app_name = row['name']
    bc = row['business_criticality']
    data = output.loc[(output['App Name'] == app_name)]
    for index in data.index:
        output.at[index, 'Business Criticality'] = bc

In [53]:
diff = snow.join(output.set_index('App Name'), on='App Name')

for index in diff.index:
    if diff.iloc[index]['name'] is not diff.iloc[index]['App Name']:
        print(diff.iloc[index]['name', 'business_criticality', 'business_criticality'])
    if diff.iloc[index]['business_criticality'] is not diff.iloc[index]['business_criticality']:
        print(diff.iloc[index]['name', 'business_criticality', 'business_criticality'])
        
print(diff[['name', 'business_criticality', 'Business Criticality']])

                name business_criticality Business Criticality
0         ACL Suites                 High                 High
0         ACL Suites                 High                 High
0         ACL Suites                 High                 High
1               ADMI                  Low                  Low
1               ADMI                  Low                  Low
..               ...                  ...                  ...
14  go.geisinger.org                  Low                  Low
14  go.geisinger.org                  Low                  Low
14  go.geisinger.org                  Low                  Low
14  go.geisinger.org                  Low                  Low
14  go.geisinger.org                  Low                  Low

[194 rows x 3 columns]

In [54]:
output.to_csv('output.csv')
output

,Server ID,App ID,App Name,Business Criticality,PLA Owner,L1 Capability,Environment,Normalized Env,Final Disposition
30,ghsacldb1w16v,APM0001678,ACL Suites,High,"Jones, Melissa M",Clinical,Production,Production,Rehost
29,ghsaclrbt1w19v,APM0001678,ACL Suites,High,"Jones, Melissa M",Clinical,Production,Production,Rehost
28,ghsaclapp1w16v,APM0001678,ACL Suites,High,"Jones, Melissa M",Clinical,Production,Production,Rehost
94,ghssdmongo1w16v,APM0002399,ADMI,Low,"Temmel, Darryl J",Clinical,Production,Production,Net New
98,ghssdstg1w16v,APM0002399,ADMI,Low,"Temmel, Darryl J",Clinical,Production,Production,Net New
...,...,...,...,...,...,...,...,...,...
139,ghssdstg1w16v,APM0002324,go.geisinger.org,Low,"Temmel, Darryl J",Corporate Services,Production,Production,Net New
140,lofsdext1w16v,APM0002324,go.geisinger.org,Low,"Temmel, Darryl J",Corporate Services,Production,Production,Net New
141,lofsdint1w16v,APM0002324,go.geisinger.org,Low,"Temmel, Darryl J",Corporate Services,Production,Production,Net New
142,lofsdmongo1w16v,APM0002324,go.geisinger.org,Low,"Temmel, Darryl J",Corporate Services,Production,Production,Net New
143,lofsdsql1w12v,APM0002324,go.geisinger.org,Low,"Temmel, Darryl J",Corporate Services,Production,Production,Net New